# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bldg',
            name='Postal_Code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
