# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgs', '0002_bldg_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bldg',
            name='District_Steam_Use_kBtu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='ENERGY_STAR_Score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Electricity_Use_Grid_Purchase_and_Generated_from_Onsite_Renewable_Systems_kBtu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Fuel_Oil_2_Use_kBtu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Natural_Gas_Use_kBtu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Number_of_Buildings',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Philadelphia_Building_ID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Portfolio_Manager_ID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Primary_Property_Type_EPA_Calculated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Property_Floor_Area_Buildings_and_Parking',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Site_EUI_kBtu_per_ftA_squared',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Source_EUI_kBtu_per_ftA_squared',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Total_GHG_Emissions_MtCO2e',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Water_Use_All_Water_Sources_kgal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bldg',
            name='Year_Built',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bldg',
            name='Postal_Code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bldg',
            name='Property_Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
