# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldgs', '0003_auto_20160227_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bldg',
            new_name='EnergyUsageLargeCommercialBuildingsReported2014',
        ),
    ]
