# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgs', '0004_auto_20160227_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusagelargecommercialbuildingsreported2014',
            name='Source_EUI_kBtu_per_ftA_squared',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='energyusagelargecommercialbuildingsreported2014',
            name='Total_GHG_Emissions_MtCO2e',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='energyusagelargecommercialbuildingsreported2014',
            name='Water_Use_All_Water_Sources_kgal',
            field=models.IntegerField(null=True),
        ),
    ]
