# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldgs', '0005_auto_20160227_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energyusagelargecommercialbuildingsreported2014',
            options={'verbose_name': 'Building Portfolio', 'verbose_name_plural': 'Building Portfolios'},
        ),
    ]
